$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'APP_NAME'
  app.version = "APP.VERSION"

  app.files += Dir.glob(File.join(app.project_dir, 'vendor/BubbleWrap/lib/**/*.rb'))
  app.files_dependencies "app/app_delegate.rb" => "app/parse_model.rb"

  app.libs << '/usr/lib/libz.1.1.3.dylib'
  app.frameworks += [
        'AudioToolbox',
        'CFNetwork',
        'SystemConfiguration',
        'MobileCoreServices',
        'Security',
        'QuartzCore']
  app.vendor_project('vendor/Parse.framework', :static,
      :products => ['Parse'],
      :headers_dir => 'Headers')
end
